var EQ_workingSetList = [
{name: 'arc.arc-core.main', path:'arcarc-coremain'},
{name: 'arc.backends.backend-android.main', path:'arcbackendsbackend-androidmain'},
{name: 'arc.backends.backend-headless.main', path:'arcbackendsbackend-headlessmain'},
{name: 'arc.backends.backend-robovm.main', path:'arcbackendsbackend-robovmmain'},
{name: 'arc.backends.backend-sdl.main', path:'arcbackendsbackend-sdlmain'},
{name: 'arc.extensions.arcnet.main', path:'arcextensionsarcnetmain'},
{name: 'arc.extensions.box2d.main', path:'arcextensionsbox2dmain'},
{name: 'arc.extensions.discord.main', path:'arcextensionsdiscordmain'},
{name: 'arc.extensions.filedialogs.main', path:'arcextensionsfiledialogsmain'},
{name: 'arc.extensions.flabel.main', path:'arcextensionsflabelmain'},
{name: 'arc.extensions.freetype.main', path:'arcextensionsfreetypemain'},
{name: 'arc.extensions.fx.main', path:'arcextensionsfxmain'},
{name: 'arc.extensions.g3d.main', path:'arcextensionsg3dmain'},
{name: 'arc.extensions.packer.main', path:'arcextensionspackermain'},
{name: 'arc.extensions.profiling.main', path:'arcextensionsprofilingmain'},
{name: 'arc.extensions.recorder.main', path:'arcextensionsrecordermain'},
{name: 'arc.extensions.tiled.main', path:'arcextensionstiledmain'},
];
